/**
 * --------------------------------------------------------------------
 * docmd : the minimalist, zero-config documentation generator.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025 docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

const path = require('path');
const fs = require('fs').promises;

async function onPostBuild({ config, pages, outputDir, log }) {
  // Validation
  if (!config.siteUrl) {
    if (log) log('⚠️  Skipping llms.txt: "siteUrl" is missing in config.');
    return;
  }

  const siteUrl = config.siteUrl.replace(/\/$/, '');
  const options = config.plugins?.llms || {};
  
  if (log) log('🤖 Generating llms.txt...');

  // Build Content
  let content = `# ${config.siteTitle} Documentation\n\n`;
  content += `> Generated by docmd\n\n`;

  if (config.description) {
    content += `${config.description}\n\n`;
  }

  content += `## Documentation Files\n\n`;

  // Filter and Sort Pages
  const validPages = pages.filter(p => {
    // Skip noindex pages or pages explicitly excluded from llms
    if (p.frontmatter.noindex) return false;
    if (p.frontmatter.llms === false) return false;
    return true;
  });

  // Sort by URL for stability
  validPages.sort((a, b) => a.outputPath.localeCompare(b.outputPath));

  // Generate Links
  for (const page of validPages) {
    let relativeUrl = page.outputPath;
    
    // Clean URL logic (match sitemap behavior)
    if (relativeUrl.endsWith('/index.html')) {
        relativeUrl = relativeUrl.replace('/index.html', '/');
    } else if (relativeUrl.endsWith('index.html')) {
        relativeUrl = '';
    }
    
    const fullUrl = `${siteUrl}/${relativeUrl}`;
    const title = page.frontmatter.title || 'Untitled';
    
    content += `- [${title}](${fullUrl})\n`;
    
    if (page.frontmatter.description) {
      content += `  ${page.frontmatter.description}\n`;
    }
  }

  // Write File
  await fs.writeFile(path.join(outputDir, 'llms.txt'), content);
}

module.exports = { onPostBuild };