/**
 * --------------------------------------------------------------------
 * docmd : the minimalist, zero-config documentation generator.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025 docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

const path = require('path');
const fs = require('fs').promises;

async function onPostBuild({ config, pages, outputDir, log }) {
  // Validation
  if (!config.siteUrl) {
    if (log) log('⚠️  Skipping llms.txt: "siteUrl" is missing in config.');
    return;
  }

  const siteUrl = config.siteUrl.replace(/\/$/, '');
  const options = config.plugins?.llms || {};

  if (log) log('🤖 Generating llms.txt...');

  // Build Content
  let content = `# ${config.siteTitle} Documentation\n\n`;
  content += `> Generated by docmd\n\n`;

  if (config.description) {
    content += `${config.description}\n\n`;
  }

  content += `## Documentation Files\n\n`;

  // Filter and Sort Pages
  const validPages = pages.filter(p => {
    // Skip noindex pages or pages explicitly excluded from llms
    if (p.frontmatter.noindex) return false;
    if (p.frontmatter.llms === false) return false;
    return true;
  });

  // Sort by URL for stability
  validPages.sort((a, b) => a.outputPath.localeCompare(b.outputPath));

  // Generate Links
  for (const page of validPages) {
    let relativeUrl = page.outputPath;

    // Clean URL logic (match sitemap behavior)
    if (relativeUrl.endsWith('/index.html')) {
      relativeUrl = relativeUrl.replace('/index.html', '/');
    } else if (relativeUrl.endsWith('index.html')) {
      relativeUrl = '';
    }

    const fullUrl = `${siteUrl}/${relativeUrl}`;
    const title = page.frontmatter.title || 'Untitled';

    content += `- [${title}](${fullUrl})\n`;

    if (page.frontmatter.description) {
      content += `  ${page.frontmatter.description}\n`;
    }
  }

  // Write llms.txt File
  await fs.writeFile(path.join(outputDir, 'llms.txt'), content);

  // Generate llms-full.txt containing the entire raw markdown concatenated
  if (log) log('🤖 Generating llms-full.txt for comprehensive AI context...');
  let fullContent = `# ${config.siteTitle || 'Documentation'} - Full Context\n\n`;
  fullContent += `> Generated by docmd\n\n`;
  if (config.description) fullContent += `${config.description}\n\n`;
  fullContent += `---\n\n`;

  for (const page of validPages) {
    let relativeUrl = page.outputPath;
    if (relativeUrl.endsWith('/index.html')) relativeUrl = relativeUrl.replace('/index.html', '/');
    else if (relativeUrl.endsWith('index.html')) relativeUrl = '';
    const fullUrl = `${siteUrl}/${relativeUrl}`;
    const title = page.frontmatter.title || 'Untitled';

    fullContent += `## [${title}](${fullUrl})\n\n`;
    try {
      if (page.sourcePath) {
        const rawMd = await fs.readFile(page.sourcePath, 'utf8');
        fullContent += `${rawMd}\n\n---\n\n`;
      } else {
        fullContent += `*(Raw content unavailable)*\n\n---\n\n`;
      }
    } catch (e) {
      if (log) log(`⚠️ Failed to read raw markdown for ${page.sourcePath}`);
    }
  }

  await fs.writeFile(path.join(outputDir, 'llms-full.txt'), fullContent);
}

module.exports = { onPostBuild };