/**
 * --------------------------------------------------------------------
 * docmd : the minimalist, zero-config documentation generator.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025 docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

const fs = require('fs/promises');
const path = require('path');

async function onPostBuild({ config, pages, outputDir, log }) {
    const pwaConfig = config.plugins?.pwa || {};
    if (pwaConfig.enabled === false) return; // Enabled by default if loaded

    if (log) log('📱 Generating PWA assets...');

    let icons = pwaConfig.icons;
    if (!icons) {
        let logoUrl = pwaConfig.logo;
        if (!logoUrl && config.logo) {
            if (typeof config.logo === 'string') logoUrl = config.logo;
            else if (config.logo.light) logoUrl = config.logo.light;
        }
        if (!logoUrl && config.favicon) {
            logoUrl = config.favicon;
        }

        if (logoUrl) {
            const cleanUrl = logoUrl.startsWith('http') ? logoUrl : (logoUrl.startsWith('/') ? logoUrl : `/${logoUrl}`);
            icons = [
                { src: cleanUrl, sizes: '192x192', type: 'image/png' },
                { src: cleanUrl, sizes: '512x512', type: 'image/png' }
            ];
        }
    }

    const manifest = {
        name: config.siteTitle || 'Documentation',
        short_name: config.siteTitle || 'Docs',
        description: config.description || 'Documentation generated by docmd',
        start_url: './',
        display: 'standalone',
        background_color: pwaConfig.bgColor || '#ffffff',
        theme_color: pwaConfig.themeColor || '#1e293b',
    };
    if (icons) manifest.icons = icons;

    await fs.writeFile(
        path.join(outputDir, 'manifest.webmanifest'),
        JSON.stringify(manifest, null, 2)
    );

    // Generate a basic Service Worker for offline caching
    const swContent = `
    const CACHE_NAME = 'docmd-cache-${Date.now()}';
    
    self.addEventListener('install', (event) => {
      self.skipWaiting();
    });

    self.addEventListener('activate', (event) => {
      event.waitUntil(
        caches.keys().then((cacheNames) => {
          return Promise.all(
            cacheNames.map((cacheName) => {
              if (cacheName !== CACHE_NAME && cacheName.startsWith('docmd-cache-')) {
                return caches.delete(cacheName);
              }
            })
          );
        }).then(() => self.clients.claim())
      );
    });

    self.addEventListener('fetch', (event) => {
      if (event.request.method !== 'GET') return;
      
      event.respondWith(
        caches.match(event.request).then((cachedResponse) => {
          if (cachedResponse) {
             // Return cached, but optionally fetch in background to update cache
             fetch(event.request).then(response => {
                if(response && response.status === 200 && response.type === 'basic' && !response.redirected) {
                   const responseToCache = response.clone();
                   caches.open(CACHE_NAME).then(cache => {
                     cache.put(event.request, responseToCache);
                   });
                }
             }).catch(() => {});
             return cachedResponse;
          }
          
          return fetch(event.request).then((response) => {
            // Safari WebKit Strict Security Policy: Service Workers cannot blindly use cache.put on redirected streams.
            // Rather than returning a 302 (Response.redirect) which triggers loop vulnerabilities in some SPAs,
            // we synthesize a literal clone of the stream masking the redirected boolean flag.
            let cacheResponse = response.clone();
            let returnResponse = response;
            
            if (response && response.redirected) {
                const clonedStream = response.clone().body;
                const headers = new Headers(response.headers);
                cacheResponse = new Response(clonedStream, {
                    headers: headers,
                    status: response.status,
                    statusText: response.statusText,
                });
                returnResponse = cacheResponse.clone();
            }

            if(!response || response.status !== 200 || response.type !== 'basic') {
              return returnResponse;
            }
            
            caches.open(CACHE_NAME)
              .then((cache) => {
                cache.put(event.request, cacheResponse);
              });
            return returnResponse;
          });
        })
      );
    });
  `;

    await fs.writeFile(
        path.join(outputDir, 'service-worker.js'),
        swContent.trim()
    );
}

function generateMetaTags(config) {
    const pwaConfig = config.plugins?.pwa || {};
    if (pwaConfig.enabled === false) return '';

    const themeColor = pwaConfig.themeColor || '#1e293b';

    return `
<link rel="manifest" href="/manifest.webmanifest">
<meta name="theme-color" content="${themeColor}">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
`;
}

function generateScripts(config) {
    const pwaConfig = config.plugins?.pwa || {};
    if (pwaConfig.enabled === false) return {};

    const swRegistration = `
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        // Use relative path for PWA SW registration to support nested deployments
        const swPath = window.DOCMD_SITE_ROOT ? window.DOCMD_SITE_ROOT + 'service-worker.js' : './service-worker.js';
        navigator.serviceWorker.register(swPath).then(reg => {
          // Check for Service Worker updates from the server every 5 minutes 
          setInterval(() => {
             reg.update().catch(() => {});
          }, 5 * 60 * 1000);
        }).catch(err => {
          console.log('PWA SW Registration Failed:', err);
        });
      });
    }
  </script>
  `;

    return { headScriptsHtml: swRegistration };
}

module.exports = { onPostBuild, generateMetaTags, generateScripts };
